[theme]
base="light"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[server]
headless=true
enableXsrfProtection=true
enableCORS=true
enableWebsocketCompression=false

[browser]
gatherUsageStats=false
